title: PT Subang Jaya Lestari
description: Perusahaan penyedia jasa konstruksi di Indonesia
base_url: ""
url: "https://www.subangjayalestari.com"
locale: id_ID

collections: 
  navbar:
    output: true
    permalink: /:path

plugins:
  - jekyll-loading-lazy