title: PT Subang Jaya Lestari Baru
description: >-
  PT Subang Jaya Lestari Baru merupakan perusahaan pengembang dan 
  penyedia jasa konstruksi yang didirikan pada tanggal 2 Oktober 2013 
  dengan direksi awal Bapak Aming Krisnanto dan Bapak Gunaedi.
base_url: ""
url: "https://www.subangjayalestari.com"

collections: 
  navbar:
    output: true
    permalink: /:path

plugins:
  - jekyll-loading-lazy
  - jekyll-sitemap