title: PT Subang Jaya Lestari
description: PT Subang Jaya Lestari baru didirikan pada tanggal 2 Oktober 2013 dengan direksi awal Bapak Aming Krisnanto dan Bapak Gunaedi. Semua proyek dikelola di wilayah Cikarang dan Subang kemudian berkembang luas ke daerah Karawang, Cikampek, Bogor, Cilegon, Serang Baru dan sekitarnya.
base_url: ""
url: "https://www.subangjayalestari.com"
locale: id_ID

collections: 
  navbar:
    output: true
    permalink: /:path

plugins:
  - jekyll-seo-tag
  - jekyll-spaceship
  - jekyll-loading-lazy